#ifndef APP_VERSION_H
#define APP_VERSION_H
#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 3
#define APP_VERSION_PATCH 1
#define APP_VERSION_BUILD 0
#define APP_VERSION_STR "0.3.1"
#endif /* APP_VERSION_H */
